// dsh-arrowkey-nav — browser half (client module-loader bundle).
// Generated by scripts/build-client.mjs from src/client/*.ts; edit the sources, not this file.
window.__ModuleLoader__.load({
  id: "dsh-arrowkey-nav",
  factory: (require) => {
    const module = { exports: {} };
    const exports = module.exports;
    /**
     * Browser-half constants: the keys this plugin owns and the DOM anchors it
     * reads. Every selector here is taken from the shipped client contract, not
     * invented; the evidence is recorded in the plan's `contract.md`.
     */
    /** Arrow key → step direction. Up/Left move backwards, Down/Right forwards. */
    const DELTA = {
        ArrowUp: -1,
        ArrowDown: 1,
        ArrowLeft: -1,
        ArrowRight: 1,
    };
    /** Group key the workspace browser uses for sessions outside every workspace. */
    const UNGROUPED = '';
    /** Slot anchor the renderer wraps around the sidebar browsing region. */
    const SIDEBAR_SCOPE = '[data-slot="sidebar.workspaces"]';
    /**
     * The one scrolling element in the sidebar (`.list`, `overflow-y: auto`).
     * Scoped to the sidebar region because other trees in the app also use
     * `role="tree"` (the JSON tree and the subagent lineage panel).
     */
    const TREE = '[role="tree"]';
    /** A workspace group header row: authored `aria-expanded`, no `data-*`. */
    const HEADER = 'div[role="treeitem"][aria-expanded]';
    /** A session row: authored `aria-selected`; search results use a `button`. */
    const ROW = 'div[role="treeitem"][aria-selected]';
    /** The composer's editable surface, an authored attribute on a contenteditable div. */
    const COMPOSER = '[data-composer-input]';
    /** Selectors of surfaces that own their own arrow keys. */
    const EDITABLE_SELECTOR = [
        'input',
        'textarea',
        'select',
        '[contenteditable=""]',
        '[contenteditable="true"]',
        '[role="textbox"]',
    ].join(', ');
    /** Selectors of overlays that own their own arrow keys. */
    const OVERLAY_SELECTOR = [
        '[role="dialog"]',
        '[role="menu"]',
        '[role="listbox"]',
        '[aria-modal="true"]',
    ].join(', ');
    /**
     * Narrow waist of the plugin: the only place that reads the two client
     * controller snapshots, and the only place that depends on their field names.
     *
     * The browser half declares no dependency on the `@deepseek-ai/*` packages — a
     * value import from a feature package is forbidden by the client purity gate,
     * and this plugin never needs one at runtime. What it does touch is a handful
     * of leaf fields, mirrored below. When dsh changes those fields, this file
     * and `apply.ts` are the only files to revisit.
     */
    /**
     * Resolve the workspace that accounts for a session.
     * @param items - workspace rows in host order.
     * @param sessionId - session whose owning workspace is required.
     * @returns the owning workspace id, or undefined when none accounts for it.
     */
    function owningWorkspaceId(items, sessionId) {
        if (sessionId === undefined)
            return undefined;
        for (const item of items) {
            if (item.sessionIds.includes(sessionId))
                return item.workspaceId;
        }
        return undefined;
    }
    /**
     * Whether the sidebar draws a session as a row. Mirrors the shipped
     * `sessionVisible`: subagent children live under their parent's
     * catalog, archived sessions are hidden everywhere, and a blank placeholder
     * is drawn only while it is the selected session.
     * @param summary - the session's list row, when the pull has reached it.
     * @param id - the session's identity.
     * @param current - currently selected session.
     * @param archived - registry-global archive set.
     * @returns true when the sidebar draws this session as a row.
     */
    function isVisibleRow(summary, id, current, archived) {
        if (summary === undefined)
            return false;
        if (summary.origin === 'subagent')
            return false;
        if (archived.has(id))
            return false;
        if (summary.blank === true && id !== current)
            return false;
        return true;
    }
    /**
     * The visible session rows of one workspace, in the browser's stored order.
     * @param workspace - workspace whose ordered membership is projected.
     * @param state - the two snapshots.
     * @returns session ids that the sidebar draws under that workspace.
     */
    function visibleRows(workspace, state) {
        const archived = new Set(state.archivedSessionIds);
        const rows = [];
        for (const id of workspace.sessionIds) {
            if (!isVisibleRow(state.list.byId[id], id, state.list.current, archived))
                continue;
            rows.push(id);
        }
        return rows;
    }
    /** The most recently updated session of a set. */
    function newestOf(rows, state) {
        let best;
        let bestAt = Number.NEGATIVE_INFINITY;
        for (const id of rows) {
            const summary = state.list.byId[id];
            if (summary === undefined)
                continue;
            if (summary.updatedAt > bestAt) {
                bestAt = summary.updatedAt;
                best = id;
            }
        }
        return best;
    }
    /**
     * Resolve one arrow key against the live snapshots.
     *
     * `order` is the sequence the sidebar is drawing for the workspace that owns
     * the current session, when it could be read. It is authoritative because the
     * sidebar does not render the controller's membership verbatim: it reconciles
     * that membership with its own persisted order and promotes recently-active
     * sessions to the top, so the two disagree in exactly the case a user notices —
     * the session they just activated. Without it, the controller's order is the
     * fallback, which is right whenever nothing has been reordered or promoted.
     * @param key - a KeyboardEvent key value.
     * @param state - the two snapshots.
     * @param order - the drawn row order of the owning workspace, when known.
     * @returns the target, or null when the key is irrelevant or the move is a no-op.
     */
    function planArrow(key, state, order) {
        const current = state.list.current;
        const owner = owningWorkspaceId(state.items, current);
        if (key === 'ArrowUp' || key === 'ArrowDown') {
            if (owner === undefined || current === undefined)
                return null;
            const workspace = state.items.find(item => item.workspaceId === owner);
            if (workspace === undefined)
                return null;
            const rows = order ?? visibleRows(workspace, state);
            if (rows.length < 2)
                return null;
            const step = key === 'ArrowDown' ? 1 : -1;
            const index = rows.indexOf(current);
            const next = rows[(index + step + rows.length) % rows.length];
            if (next === undefined || next === current)
                return null;
            return { kind: 'session', sessionId: next, rowIndex: rows.indexOf(next), workspaceId: owner };
        }
        if (key === 'ArrowLeft' || key === 'ArrowRight') {
            if (state.items.length < 2)
                return null;
            const step = key === 'ArrowRight' ? 1 : -1;
            // A session no workspace accounts for — or no selection at all — has no
            // position in the order. Entering at the end the key implies keeps the
            // direction the user asked for; entering at index 0 would make ArrowLeft
            // move forwards.
            const index = owner === undefined ? -1 : state.items.findIndex(item => item.workspaceId === owner);
            const from = index === -1 && step < 0 ? state.items.length : index;
            const target = state.items[(from + step + state.items.length) % state.items.length];
            if (target === undefined || target.workspaceId === owner)
                return null;
            return { kind: 'workspace', workspaceId: target.workspaceId };
        }
        return null;
    }
    /**
     * DOM layer: read-only lookups with a single write — bringing the target row
     * into view. Rows carry no identity attributes (no `data-*`, no `id`), so the
     * DOM is never asked "which session is this"; identity comes from the
     * controller snapshots and the DOM is addressed positionally.
     *
     * Every lookup is total: a missing anchor, a collapsed group, a rail-collapsed
     * sidebar, or an ambiguous binding all resolve to "no scroll", never to a guess.
     */
    /** The sidebar's scrolling element, or null when the tree is not mounted. */
    function sidebarScroller() {
        try {
            return document.querySelector(`${SIDEBAR_SCOPE} ${TREE}`);
        }
        catch {
            // A malformed selector or a detached document is not worth a failure here.
            return null;
        }
    }
    /**
     * The session ids of one workspace in the order the sidebar currently draws
     * them.
     *
     * This is the order arrow keys must follow. The sidebar does not render the
     * controller's `sessionIds` verbatim: it reconciles them with its own persisted
     * order and promotes recently-activated sessions to the top, so the controller
     * order and the visible order can disagree. Reading the rendered order asks the
     * question the user is actually answering — "which row is above this one?" —
     * without reproducing that policy.
     *
     * The order is trusted only when the section's labels account for every row the
     * controller reports for the workspace: the same count, and the same multiset of
     * labels. That check tolerates reordering while refusing a section that is
     * showing a different set of sessions (another workspace's group, or a filtered
     * list). Anything short of that falls back to the controller order.
     * @param state - the two controller snapshots.
     * @param labels - row label text per session.
     * @param firstView - whether the workspace shows a "new session" placeholder.
     * @returns the drawn session ids per workspace.
     */
    function displayOrder(state, labels, firstView) {
        const drawn = new Map();
        const scroller = sidebarScroller();
        if (scroller === null)
            return drawn;
        // A scroller that is not the tree this plugin expects must degrade to the
        // controller order, never fail the key press: one malformed lookup here would
        // otherwise disable every arrow key at once.
        let sections;
        try {
            sections = groupSections(scroller);
        }
        catch {
            return drawn;
        }
        for (const workspace of state.items) {
            const expected = controllerRows(workspace, state, firstView);
            if (expected.length === 0)
                continue;
            try {
                const match = sections.filter(candidate => accountsFor(drawnLabels(candidate), expected, labels));
                if (match.length !== 1)
                    continue;
                const resolved = resolveLabels(drawnLabels(match[0] ?? scroller), expected, labels);
                if (resolved.length === expected.length)
                    drawn.set(workspace.workspaceId, resolved);
            }
            catch {
                // One unreadable section keeps that workspace on the controller order.
                continue;
            }
        }
        return drawn;
    }
    /**
     * The rows the controller says belong to a workspace, including the selected
     * blank placeholder when the workspace holds one.
     *
     * A blank placeholder is drawn only while it is selected, which makes the
     * shared `visibleRows` predicated on the currently selected session alone; the
     * sidebar's own grouping admits a blank of any workspace. Widening it here keeps
     * the comparison against a rendered section honest.
     * @param workspace - workspace whose rows are listed.
     * @param state - the two controller snapshots.
     * @param firstView - blank placeholders visible across all workspaces.
     * @returns session ids in controller order.
     */
    function controllerRows(workspace, state, firstView) {
        const archived = new Set(state.archivedSessionIds);
        const placeholders = new Set(firstView);
        const rows = [];
        for (const id of workspace.sessionIds) {
            const summary = state.list.byId[id];
            if (summary === undefined)
                continue;
            if (summary.origin === 'subagent')
                continue;
            if (archived.has(id))
                continue;
            if (summary.blank === true && !placeholders.has(id))
                continue;
            rows.push(id);
        }
        return rows;
    }
    /** Whether a section's drawn labels account for exactly the expected rows. */
    function accountsFor(actual, expected, labels) {
        const wanted = expected.map(id => labels.get(id));
        if (wanted.some(label => label === undefined))
            return false;
        const remaining = [...wanted].sort();
        const drawn = [...actual].sort();
        if (remaining.length !== drawn.length)
            return false;
        return remaining.every((label, index) => label === drawn[index]);
    }
    /**
     * Map a section's drawn rows back to session ids.
     *
     * Labels are matched in order, each label consumed once, so duplicated titles
     * resolve to distinct sessions rather than collapsing onto one.
     */
    function resolveLabels(actual, expected, labels) {
        const available = new Map();
        for (const id of expected) {
            const label = labels.get(id);
            if (label === undefined)
                continue;
            const bucket = available.get(label);
            if (bucket === undefined)
                available.set(label, [id]);
            else
                bucket.push(id);
        }
        const resolved = [];
        for (const label of actual) {
            const bucket = available.get(label);
            const id = bucket?.shift();
            if (id === undefined)
                return [];
            resolved.push(id);
        }
        return resolved;
    }
    /**
     * Bring one target's row into view.
     * @param target - the resolved session target.
     * @param order - the drawn session ids of the target's workspace.
     * @param labels - row label text per session.
     */
    function scrollToRow(target, order, labels) {
        if (target.kind !== 'session')
            return;
        try {
            const section = sectionFor(order, labels);
            if (section === null)
                return;
            const row = Array.from(section.querySelectorAll(ROW))[target.rowIndex];
            if (row === undefined || typeof row.scrollIntoView !== 'function')
                return;
            row.scrollIntoView({ block: 'nearest' });
        }
        catch {
            // Scrolling is a courtesy; the selection has already moved.
        }
    }
    /**
     * The group section drawing exactly the given rows.
     * @param expected - session ids the workspace should be drawing.
     * @param labels - row label text per session.
     * @returns the section, or null when none accounts for the rows or several do.
     */
    function sectionFor(expected, labels) {
        if (expected.length === 0)
            return null;
        const scroller = sidebarScroller();
        if (scroller === null)
            return null;
        const matches = groupSections(scroller)
            .filter(candidate => accountsFor(drawnLabels(candidate), expected, labels));
        return matches.length === 1 ? matches[0] ?? null : null;
    }
    /** The group sections of the sidebar tree, in document order. */
    function groupSections(scroller) {
        return Array.from(scroller.children);
    }
    /** Whether the composer owned focus when the key was pressed. */
    function composerHadFocus() {
        try {
            const active = document.activeElement;
            if (active === null)
                return false;
            return active.closest(COMPOSER) !== null;
        }
        catch {
            return false;
        }
    }
    /**
     * Whether the composer holds no draft.
     *
     * An empty composer has nothing for an arrow key to do — there is no caret to
     * move through text — so navigation may take the key. Once a draft exists the
     * key belongs to the caret again.
     * @returns true when the composer is absent or its text is blank.
     */
    function composerDraftIsEmpty() {
        try {
            const composer = document.querySelector(COMPOSER);
            if (composer === null)
                return true;
            return String(composer.textContent ?? '').trim() === '';
        }
        catch {
            // Unknown state: leave the key with the composer rather than navigate.
            return false;
        }
    }
    /**
     * Put focus back into the composer.
     *
     * Only a DOM-level focus call: the composer is a `contenteditable` div, so
     * there is no selection range to restore and no draft to touch.
     */
    function focusComposer() {
        try {
            // `document.querySelector` is typed as `Element`; focus lives on
            // `HTMLElement`, so the narrowing is asserted here and re-checked at runtime
            // rather than trusting an unchecked cast with an `any`.
            const composer = document.querySelector(COMPOSER);
            if (composer === null)
                return;
            if (typeof composer.focus !== 'function')
                return;
            composer.focus({ preventScroll: true });
        }
        catch {
            // Losing focus is recoverable by clicking; never break the key handler.
        }
    }
    /** The label text drawn for each row element in one section. */
    function drawnLabels(section) {
        return Array.from(section.querySelectorAll(ROW)).map((row) => {
            const title = row.querySelector('[class*="_title"]');
            return labelText(title ?? row);
        });
    }
    /** Normalize element text for label comparison. */
    function labelText(element) {
        return String(element.textContent ?? '').replace(/\s+/g, ' ').trim();
    }
    /**
     * Execution layer: turn one resolved target into client-side effects.
     *
     * The whole switching path is `sessions.open`. The details panel is not this
     * plugin's business: the shipped frame already closes it whenever the current
     * session changes, and the running build exposes no `selectPanel`.
     */
    /**
     * Adopt one workspace the way the sidebar does.
     *
     * Precedence: the workspace's blank placeholder, then its most recently
     * updated visible session, then the shipped `connectWorkspace` (which creates a
     * blank session there). The first two are this plugin's product choice: always
     * creating would leave a trail of empty sessions behind every arrow press.
     * @param plan - the three service faces.
     * @param workspaceId - target workspace.
     */
    function openWorkspace(plan, workspaceId, order) {
        const workspace = plan.workspaces.list.getSnapshot().items
            .find(item => item.workspaceId === workspaceId);
        if (workspace === undefined)
            return;
        const state = readState(plan);
        const rows = order ?? visibleRows(workspace, state);
        const blank = blankSessionFor(workspace, state, rows);
        if (blank !== undefined) {
            plan.sessions.open(blank);
            return;
        }
        const newest = newestOf(rows, state);
        if (newest !== undefined) {
            plan.sessions.open(newest);
            return;
        }
        void plan.uiWorkspace.connectWorkspace(workspaceId)
            .then((sessionId) => { plan.sessions.open(sessionId); }, () => {
            // A workspace that cannot be connected leaves the selection alone;
            // the next press retries. Nothing to report: this plugin has no UI.
        });
    }
    /**
     * Apply one resolved target.
     * @param plan - the three service faces.
     * @param target - the target `planArrow` returned.
     * @param order - the drawn order of the target workspace, when it was read: the
     *   landing session then follows what the user sees rather than the controller's
     *   membership order.
     */
    function execute(plan, target, order) {
        if (target.kind === 'session') {
            plan.sessions.open(target.sessionId);
            return;
        }
        openWorkspace(plan, target.workspaceId, order);
    }
    /**
     * The workspace's reusable blank session, using the shipped predicate: it must
     * be a blank whose `cwd` is this workspace's path and which the registry has
     * not archived. The `cwd` test keeps a stale blank from another directory out.
     * @param workspace - workspace being entered.
     * @param state - the two snapshots.
     * @param rows - the rows the sidebar is drawing for this workspace.
     * @returns the blank session id, or undefined when the workspace has none.
     */
    function blankSessionFor(workspace, state, rows) {
        const archived = new Set(state.archivedSessionIds);
        for (const id of rows) {
            const summary = state.list.byId[id];
            if (summary === undefined)
                continue;
            if (summary.blank !== true)
                continue;
            if (archived.has(id))
                continue;
            if (summary.cwd !== workspace.path)
                continue;
            return id;
        }
        return undefined;
    }
    /** Read the two snapshots the navigation layer resolves against. */
    function readState(plan) {
        const workspaces = plan.workspaces.list.getSnapshot();
        return {
            items: workspaces.items,
            archivedSessionIds: workspaces.archivedSessionIds,
            list: plan.sessions.list.getSnapshot(),
        };
    }
    /**
     * Binding layer: one capturing keydown listener on the document.
     *
     * The listener is attached from `apply`, not from a rendered component: the two
     * facts an arrow press needs are the key itself and the current focus, and
     * neither requires a React tree. `ctx.effect` owns the listener, so unloading
     * the plugin removes it.
     */
    /**
     * Whether a keydown belongs to somebody else.
     *
     * Arrow keys are how the composer moves its caret, how a dialog moves between
     * its buttons, and how an open menu moves through its items, so the plugin
     * stays out of the way when any of those owns the event.
     *
     * The composer is the one conditional case: an empty draft has no caret to
     * move, so the key is free and navigation may take it. A draft with text keeps
     * its arrow keys — that is the difference between "I am writing" and "I am
     * browsing". Every other editable surface (the sidebar's session search, a
     * rename field) always keeps its keys.
     *
     * A modifier means the user asked for something else, and an event already
     * handled upstream has a decision attached that must not be overridden.
     * @param event - the keydown event.
     * @returns true when the plugin must not act on this event.
     */
    function shouldIgnore(event) {
        return decideIgnore(event).ignore;
    }
    /**
     * Decide one keydown: whether to leave it alone, and what that decision was.
     * One traversal serves both the guard and its diagnostic, so a press never pays
     * for the DOM twice.
     * @param event - the keydown event.
     * @returns the decision and, when ignored, the reason in plain words.
     */
    function decideIgnore(event) {
        if (event.defaultPrevented)
            return { ignore: true, reason: 'already handled upstream' };
        if (event.altKey || event.ctrlKey || event.metaKey || event.shiftKey) {
            return { ignore: true, reason: 'modifier held' };
        }
        if (event.isComposing === true)
            return { ignore: true, reason: 'IME composing' };
        const target = event.target;
        const element = target !== null && typeof target === 'object' ? target : null;
        if (element === null || typeof element.closest !== 'function')
            return { ignore: false };
        try {
            // Falsy rather than `!== null`: a real `closest` returns `Element | null`,
            // and treating any other empty result as a match would misroute the key.
            if (element.closest(OVERLAY_SELECTOR)) {
                return { ignore: true, reason: 'focus is in a dialog or menu' };
            }
            if (!element.closest(EDITABLE_SELECTOR))
                return { ignore: false };
            if (!element.closest(COMPOSER)) {
                return { ignore: true, reason: 'focus is in an editable surface' };
            }
            // The composer itself yields its arrow keys only while its draft is empty.
            return composerDraftIsEmpty()
                ? { ignore: false }
                : { ignore: true, reason: 'composer holds a draft' };
        }
        catch {
            // An unexpected node shape is not a reason to move the user's selection.
            return { ignore: true, reason: 'target shape was unexpected' };
        }
    }
    /** Read the two snapshots the navigation layer resolves against. */
    function readNavState(plan) {
        const workspaces = plan.workspaces.list.getSnapshot();
        return {
            items: workspaces.items,
            archivedSessionIds: workspaces.archivedSessionIds,
            list: plan.sessions.list.getSnapshot(),
        };
    }
    /** Row label text per session, used to bind a drawn section to its rows. */
    function rowLabels(state) {
        const labels = new Map();
        for (const workspace of state.items) {
            for (const id of workspace.sessionIds) {
                const summary = state.list.byId[id];
                if (summary === undefined)
                    continue;
                labels.set(id, summary.displayTitle);
            }
        }
        return labels;
    }
    /**
     * The blank placeholders currently visible anywhere.
     *
     * The shared visibility rule draws only the selected one; the sidebar's own
     * grouping admits the blank of whichever workspace it belongs to, so the drawn
     * order needs the wider set to compare against a rendered section honestly.
     */
    function visiblePlaceholders(state) {
        const placeholders = [];
        for (const workspace of state.items) {
            for (const id of workspace.sessionIds) {
                const summary = state.list.byId[id];
                if (summary?.blank !== true)
                    continue;
                if (state.archivedSessionIds.includes(id))
                    continue;
                placeholders.push(id);
            }
        }
        return placeholders;
    }
    /**
     * One arrow key, end to end.
     *
     * Returning false means the event was left untouched: the key was irrelevant,
     * or the move it implied was a no-op, so nothing is consumed.
     * @param plan - the three service faces.
     * @param event - the keydown event.
     * @param trace - optional report of what was decided, for diagnosing a press
     *   that does nothing. Only arrow keys reach it.
     * @returns true when the plugin acted on the event.
     */
    function handleArrowKey(plan, event, trace) {
        if (DELTA[event.key] === undefined)
            return false;
        const decision = decideIgnore(event);
        if (decision.ignore) {
            trace?.('ignored', { key: event.key, reason: decision.reason });
            return false;
        }
        const state = readNavState(plan);
        const labels = rowLabels(state);
        const drawn = displayOrder(state, labels, visiblePlaceholders(state));
        const owner = owningWorkspaceId(state.items, state.list.current);
        const order = owner === undefined ? undefined : drawn.get(owner);
        const target = planArrow(event.key, state, order);
        if (target === null) {
            trace?.('no target', {
                key: event.key,
                current: state.list.current,
                owner,
                orderFromDom: order !== undefined,
                rowsInOwner: order?.length
                    ?? (owner === undefined ? undefined : rowsOf(state, owner).length),
                workspaces: state.items.length,
            });
            return false;
        }
        event.preventDefault();
        trace?.('navigating', { ...target, orderFromDom: order !== undefined });
        // Focus intent is read at press time: only a press that started in the
        // composer puts focus back, so the sidebar's search box and open dialogs
        // keep the focus they had.
        const restoreFocus = composerHadFocus();
        execute(plan, target);
        const targetOrder = planOrder(plan, target, labels);
        requestAnimationFrame(() => {
            // React has committed the new selection by now, so the target row exists.
            scrollToRow(target, targetOrder, labels);
            if (!restoreFocus)
                return;
            requestAnimationFrame(() => { focusComposer(); });
        });
        return true;
    }
    /**
     * The drawn order to scroll against after the switch.
     *
     * The selection moved, so the freshly rendered order can differ from the one
     * the key was resolved against — a promoted session lands on top. Re-reading is
     * cheap and keeps the scroll on the row the user is about to look at.
     * @param plan - the three service faces.
     * @param target - where the switch went.
     * @param labels - row label text per session.
     * @returns the target workspace's drawn order, or its controller order as a fallback.
     */
    function planOrder(plan, target, labels) {
        const owner = target.kind === 'session' ? target.workspaceId : undefined;
        if (owner === undefined)
            return [];
        const next = readNavState(plan);
        const fresh = displayOrder(next, labels, visiblePlaceholders(next)).get(owner);
        return fresh ?? rowsOf(next, owner);
    }
    /** The controller-order rows of one workspace, including its blank placeholder. */
    function rowsOf(state, workspaceId) {
        const workspace = state.items.find(item => item.workspaceId === workspaceId);
        if (workspace === undefined)
            return [];
        const placeholders = new Set(visiblePlaceholders(state));
        const archived = new Set(state.archivedSessionIds);
        return workspace.sessionIds.filter((id) => {
            const summary = state.list.byId[id];
            if (summary === undefined)
                return false;
            if (summary.origin === 'subagent')
                return false;
            if (archived.has(id))
                return false;
            if (summary.blank === true && !placeholders.has(id))
                return false;
            return true;
        });
    }
    /** Cordis service injections this plugin waits for. */
    const inject = ['sessions', 'workspaces', 'uiWorkspace'];
    /**
     * Attach the arrow-key listener.
     * @param ctx - the plugin's Cordis context, narrowed to the services it uses.
     */
    function apply(ctx) {
        const onKeyDown = (event) => {
            try {
                handleArrowKey(ctx, event, trace);
            }
            catch (error) {
                // A broken snapshot or a re-rendered tree must not take the listener with
                // it: the next press should still work, so the failure stops here.
                console.error('dsh-arrowkey-nav: keydown failed', error);
            }
        };
        ctx.effect(() => {
            document.addEventListener('keydown', onKeyDown, true);
            // One line so a silent failure is never silent: if this does not appear,
            // the plugin never activated (a pending injection) and no key can work.
            console.info('dsh-arrowkey-nav: listener attached', {
                sessions: ctx.sessions !== undefined,
                workspaces: ctx.workspaces !== undefined,
                uiWorkspace: ctx.uiWorkspace !== undefined,
            });
            return () => {
                document.removeEventListener('keydown', onKeyDown, true);
                console.info('dsh-arrowkey-nav: listener removed');
            };
        }, 'dsh-arrowkey-nav: document keydown listener');
        // Read-only diagnostic accessor for the console (see diagnose-console.js):
        // the service snapshots live inside this closure, so a shape probe has to
        // run from here. Removed with the plugin.
        ctx.effect(() => {
            globalThis.__dshArrowkeyNav = {
                snapshot: () => {
                    try {
                        const state = readNavState(ctx);
                        const rows = Object.values(state.list.byId);
                        const sample = rows[0];
                        return {
                            services: {
                                sessions: ctx.sessions !== undefined,
                                workspaces: ctx.workspaces !== undefined,
                                uiWorkspace: ctx.uiWorkspace !== undefined,
                            },
                            sessions: {
                                snapshotKeys: Object.keys(state.list),
                                rowKeys: sample === undefined ? [] : Object.keys(sample),
                                current: state.list.current,
                                phase: state.list.phase,
                                rowCount: rows.length,
                                sampleRow: sample,
                            },
                            workspaces: {
                                workspaceCount: state.items.length,
                                workspaceKeys: state.items[0] === undefined ? [] : Object.keys(state.items[0]),
                                archivedCount: state.archivedSessionIds.length,
                                sampleWorkspace: state.items[0],
                            },
                        };
                    }
                    catch (error) {
                        return { error: String(error) };
                    }
                },
            };
            return () => {
                delete globalThis.__dshArrowkeyNav;
            };
        }, 'dsh-arrowkey-nav: console diagnostic accessor');
    }
    /**
     * Report what one arrow press decided.
     *
     * Only arrow keys are reported, so ordinary typing never reaches the console.
     * @param message - what happened.
     * @param detail - the values that decided it.
     */
    function trace(message, detail) {
        console.info(`dsh-arrowkey-nav: ${message}`, detail);
    }
    exports.inject = inject;
    exports.apply = apply;
    return module.exports;
  },
});
